print('Hello world!'.startswith('Hello'))
print('Hello world!'.endswith('world'))
print('abc123'.startswith('abcdef'))
print('abc123'.endswith('abcdef'))
print('Hello world!'.startswith('Hello World!'))
print('Hello world!'.endswith('Hello World!'))

print('Hello'.rjust(10))
print('Hello'.rjust(20))
print('Hello World'.rjust(20))
print('Hello'.ljust(10))
print('Hello'.rjust(20,'*'))
print('Hello'.ljust(20,'-'))
print('Hello'.center(20))
print('Hello'.center(20,'-'))